server:
  port: 8088
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_volunteer?serverTimezone=Asia/Shanghai
    username: root
    password: 123456




mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: false
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

weixin:
  jscode2sessionUrl: https://api.weixin.qq.com/sns/jscode2session
  appid: wxe4aafbe9a6a8a416
  secret: 6beb54248a98ff8cd20526284526def7

weixinpayconfig:
   appid: wxf503a70f1f45cbd2
   mch_id: 1500625891
   key: jrBXpyMVP1Y0FCFI42EBShLom7KMaRBa
   url: https://api.mch.weixin.qq.com/pay/unifiedorder
   notify_url: https://0c56-180-121-172-30.ngrok.io/weixinpay/notifyUrl

